### ISSUE TITLE
Error after changes

### ISSUE THREAD

**Issue by jlberrocal** [angular/angular2-seed#80] opened 2016-05-24 16:33 UTC
Hi everybody, first thanks for this awesome seed project.

Now i have a problem that occurs when i make changes over the code, when it reload the browser the console throws the following:

EXCEPTION: TypeError: dep is nullbrowser_adapter.js:86
EXCEPTION: TypeError: dep is nullbrowser_adapter.js:77:13

EXCEPTION: Error: Uncaught (in promise): TypeError: dep is nullbrowser_adapter.js:86
EXCEPTION: Error: Uncaught (in promise): TypeError: dep is nullbrowser_adapter.js:77:13

STACKTRACE:browser_adapter.js:77:13

resolvePromise@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:538:32
makeResolver/<@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:515:14
ApplicationRef_.prototype.run/</<@http://dev5-metro.alkaid.cr/node_modules/@angular/core/src/application_ref.js:295:25
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:323:20
NgZoneImpl/this.inner<.onInvoke@http://dev5-metro.alkaid.cr/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:32
Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:322:20
Zone</Zone</Zone.prototype.run@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:216:25
scheduleResolveOrReject/<@http://dev5-metro.alkaid.cr/node_modules/zone.js/dist/zone.js?1464107373967:571:53
Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://dev5-metro.alkaid[…]browser_adapter.js:77:13

Unhandled Promise rejection: dep is null ; Zone: angular ; Task: Promise.then ; Value: TypeError: dep is null
Stack trace:
[object Object]zone.js:461:14

Error: Uncaught (in promise): TypeError: dep is null

I'm running firefox developer edition under Ubuntu 15.04 (just in case)

Thanks in advance

**Comment by pkozlowski-opensource** [comment] 2016-06-27 20:26
Can't reproduce locally. Closing for now. Please open a new issue with more context + reproduce scenario.

**Closed by pkozlowski-opensource** 2016-06-27 20:26 UTC

**Comment by jlberrocal** [comment] 2016-07-06 14:31
I was able to reproduce it, it happen to my in webstorm if i enable the automatic compilation, for fix it i had to remove all compiled files and then it works again
