### ISSUE TITLE
how to build so this works with non node server

### ISSUE THREAD

**Issue by chungtinhlakho** [angular/angular2-seed#122] opened 2016-09-11 06:58 UTC
Hi, I'm hoping to use this seed to start my project, long time ago, i use the version with lite server and I was able to deploy on a non node server by building the js build.  How would I be doing that here with the new webpack?  Any direction would be greatly appreciated.  thanks

**Comment by pkozlowski-opensource** [comment] 2016-09-17 19:19
Duplicate of #17

**Closed by pkozlowski-opensource** 2016-09-17 19:19 UTC
