### ISSUE TITLE
production build with webpack

### ISSUE THREAD

**Issue by chungtinhlakho** [angular/angular2-seed#130] opened 2016-09-24 01:22 UTC
my production is in a none node server.  I was able to get this seed to work.  but was not able to build production to test if this would work on my server.  
I added "build:prod": "webpack -p --progress" to my package.json script

in webpack config, i added the below to have webpage generate my index file for me.  I was able to run npm run build:prod and was successful but when i open it on firefox, i get nothing.  can someone help point me in the right direction?  thanks
new HtmlWebPackPlugin({
            template: './src/index.html'
        })

![prod](https://cloud.githubusercontent.com/assets/1680647/18805127/aa0b9ff4-81ba-11e6-9f4a-9f2349ff8e9e.JPG)

**Comment by pkozlowski-opensource** [comment] 2016-10-03 12:40
Duplicate of #17

**Closed by pkozlowski-opensource** 2016-10-03 12:40 UTC
